web:
  image: "${DOCKER_IMAGE}"
  environment:
    - ENVIRONMENT

lb:
  ports:
    - "10080:3000"
  labels:
    io.rancher.scheduler.global: "true"
  image: "rancher/load-balancer-service"
  links:
    - "web:web"
